[versions]
ksp = "2.3.2"
kotest = "6.0.4"
kotlin-compile-testing = "0.11.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.2.21" }
kotest = { id = "io.kotest", version.ref = "kotest" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.8" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.34.0" }
dokka = { id = "org.jetbrains.dokka", version = "2.1.0" }

[libraries]
ksp-symbol-processing-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
kotest-bom = { module = "io.kotest:kotest-bom", version.ref = "kotest" }
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core" }
kotest-assertions-compiler = { module = "io.kotest:kotest-assertions-compiler" }
kotlin-compile-testing = { module = "dev.zacsweers.kctfork:core", version.ref = "kotlin-compile-testing" }
kotlin-compile-testing-ksp = { module = "dev.zacsweers.kctfork:ksp", version.ref = "kotlin-compile-testing" }

[bundles]
kotest = ["kotest-framework-engine", "kotest-assertions-core", "kotest-assertions-compiler"]
kotlin-compile-testing = ["kotlin-compile-testing", "kotlin-compile-testing-ksp"]
